# Generated by Django 5.0.4 on 2024-04-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produc',
            name='images',
        ),
        migrations.AlterField(
            model_name='produc',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produc',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produc',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produc',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
