# Generated by Django 5.0.4 on 2024-04-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_produc_images_alter_produc_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produc',
            name='images',
            field=models.ImageField(default='', upload_to='photos/product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produc',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='produc',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produc',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='produc',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
